@base_url=http://localhost:8087/api/v1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE0NDQ0Nzg0MDAsInVzZXJfaWQiOjN9.AJido-ix6ox9QTEQE7KSyQoCkZAi4OD39TGnMYP4LJ0

###

GET {{base_url}}/health-check HTTP/1.1
content-type: application/json

###

POST {{base_url}}/user/register HTTP/2.0
content-type: application/json

{
    "username": "mihai2",
    "email": "mihai2@getchip.uk",
    "password": "intrex"
}

###

POST {{base_url}}/user/login HTTP/2.0
content-type: application/json

{
    "email": "mihai@getchip.uk",
    "password": "intrex"
}

###

GET {{base_url}}/project/3 HTTP/2.0
content-type: application/json
Authorization: Bearer {{token}}

###

GET {{base_url}}/projects/user/1 HTTP/2.0
content-type: application/json
Authorization: Bearer {{token}}

###

POST {{base_url}}/project HTTP/2.0
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Prepare2",
    "color": "grey",
    "description": "intrex",
    "icon": "intrex"
}

###

DELETE {{base_url}}/project/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

PUT {{base_url}}/project/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "777",
    "color": "blue",
    "description": "intrex",
    "icon": "intrex"
}

### 

POST {{base_url}}/task HTTP/1.1
content-type: application/json

{
    "project_id": 3,
    "subtask_id": 16,
    "title": "This is a subtask",
    "note": "This is a task",
    "expire": "2020-08-20T15:04:05.000Z",
    "repeat": false,
    "priority": 1
}

###

DELETE {{base_url}}/task/11 HTTP/1.1
content-type: application/json

###

PUT {{base_url}}/task/complete/18 HTTP/1.1
content-type: application/json

