@base_url=http://localhost:8087/api/v1

###

GET {{base_url}}/health-check HTTP/1.1
content-type: application/json

###

GET {{base_url}}/project/2 HTTP/1.1
content-type: application/json

###

GET {{base_url}}/projects/user/1 HTTP/1.1
content-type: application/json

###

POST {{base_url}}/project HTTP/1.1
content-type: application/json

{
    "title": "Prepare",
    "color": "grey",
    "description": "intrex",
    "icon": "intrex"
}

###

DELETE {{base_url}}/project/2 HTTP/1.1
content-type: application/json

###

PUT {{base_url}}/project/1 HTTP/1.1
content-type: application/json

{
    "title": "777",
    "color": "blue",
    "description": "intrex",
    "icon": "intrex"
}

### 

POST {{base_url}}/task HTTP/1.1
content-type: application/json

{
    "project_id": 3,
    "subtask_id": 20,
    "title": "This is a subtask",
    "note": "This is a task",
    "expire": "2020-08-20T15:04:05.000Z",
    "repeat": false,
    "priority": 1
}

###

DELETE {{base_url}}/task/11 HTTP/1.1
content-type: application/json

###

PUT {{base_url}}/task/complete/11 HTTP/1.1
content-type: application/json

